# Generated by Django 3.0 on 2019-12-17 06:54

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=65)),
                ('task_description', models.CharField(max_length=400)),
                ('dead_line', models.DateTimeField(default=datetime.datetime(2019, 12, 17, 6, 54, 54, 333770))),
                ('task_force', models.ManyToManyField(db_index=True, default=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
