# Generated by Django 3.0 on 2019-12-17 06:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dead_line',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 6, 56, 2, 470162, tzinfo=utc)),
        ),
    ]
