# Generated by Django 3.0 on 2019-12-17 06:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20191217_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dead_line',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 6, 57, 23, 174483, tzinfo=utc)),
        ),
    ]
