# Generated by Django 3.0 on 2019-12-17 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0005_task_is_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_force',
        ),
        migrations.AddField(
            model_name='task',
            name='task_force',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
