# Generated by Django 3.0 on 2019-12-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(choices=[('request for work', 'apply'), ('upgrade job post', 'upgrade')], default=None, max_length=45)),
            ],
        ),
    ]
